### ISSUE TITLE
Error in getKey controller

### ISSUE THREAD

**Issue by surgus** [DIG-Network/chia-dig-node#23]
Today, soon after midnight this error has appear:

10:53:00 DesktopLinux docker-compose[33296]: content-server-1      | Error in getKey controller: DataLayerError: Root hash 7e6ddaf9fba610835db9d4fe7378d69e1b0dba11c9c961d54309e13760168a84 not found
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at new DataIntegrityTree (/app/node_modules/@dignetwork/dig-sdk/dist/DataIntegrityTree/DataIntegrityTree.js:101:23)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at getKey (/app/dist/controllers/storeController.js:180:27)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at next (/app/node_modules/express/lib/router/route.js:149:13)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at parseUdi (/app/dist/middleware/parseUdi.js:143:9)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at next (/app/node_modules/express/lib/router/route.js:149:13)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:119:3)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |     at /app/node_modules/express/lib/router/index.js:284:15 {
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      |   code: 404
10:53:00 DesktopLinux docker-compose[33296]: content-server-1      | }

And it repeats itself constantly.

**Comment by MichaelTaylor3D** [comment]
closing this since we addressed it offline: fix was...something was stuck and a restart unstuck it. Keeping an Eye on that.
